export const global = {
  TOGGLESEARCH: "TOGGLESEARCH",
  UNTOGGLESEARCH: "UNTOGGLESEARCH",
  LOADING: "LOADING",
  LOADINGTRUE: "LOADINGTRUE",
  SHOWPOSTS: "SHOWPOSTS",
  SHOWCOMMENTS: "SHOWCOMMENTS",
  SETMESSAGES: "SETMESSAGES",
  GETMESSAGES: "GETMESSAGES",
  GETUSERDATA: "GETUSERDATA",
  GETCHAT: "GETCHAT",
};
